### ISSUE TITLE
sniffio breakage on Focal with python 3.8.10

### ISSUE THREAD

**Issue by hloeung** [canonical/layer-basic#223]
Hi,

I built a new content-cache charm but now that's breaking on Focal:

```
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Reading state information...
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 virtualenv is already the newest version (20.0.17-1ubuntu0.4).
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 created virtual environment CPython3.8.10.final.0-64 in 75ms
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   creator CPython3Posix(dest=/var/lib/juju/agents/unit-content-cache-0/.venv, clear=False, global=False)
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
2024-03-14 14:14:52 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
2024-03-14 14:14:53 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Looking in links: wheelhouse
2024-03-14 14:14:53 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Requirement already up-to-date: pip in /var/lib/juju/agents/unit-content-cache-0/.venv/lib/python3.8/site-packages (20.0.2)
2024-03-14 14:14:54 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Looking in links: wheelhouse
2024-03-14 14:14:54 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Requirement already up-to-date: setuptools in /var/lib/juju/agents/unit-content-cache-0/.venv/lib/python3.8/site-packages (44.0.0)
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Looking in links: wheelhouse
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing /root/.cache/pip/wheels/64/c4/ef/7c321d1b6261f19941890748035728d5669ca158779fde7388/setuptools_scm-1.17.0-py2.py3-none-any.whl
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Installing collected packages: setuptools-scm
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Successfully installed setuptools-scm-1.17.0
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Looking in links: wheelhouse
2024-03-14 14:14:55 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/wheel-0.33.6.tar.gz
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/MarkupSafe-2.0.1.tar.gz
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Building wheels for collected packages: wheel, MarkupSafe
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Building wheel for wheel (setup.py): started
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Building wheel for wheel (setup.py): finished with status 'done'
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Created wheel for wheel: filename=wheel-0.33.6-py2.py3-none-any.whl size=21555 sha256=26c10621460e1eaeba55dec44ac32211a6180dd9db1b1fd2cb45f06ee2653eb3
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Stored in directory: /tmp/pip-ephem-wheel-cache-9hmt54fa/wheels/ae/a3/94/9483ff2c9978ab368be69a720568c5ed6560a998d623cb0483
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Building wheel for MarkupSafe (setup.py): started
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Building wheel for MarkupSafe (setup.py): finished with status 'done'
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Created wheel for MarkupSafe: filename=MarkupSafe-2.0.1-cp38-cp38-linux_x86_64.whl size=30804 sha256=d39b9507b7cc0bb5d18e152f9f2fe5716a6fd4a1056fc71cc93b2d0cf2b34505
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Stored in directory: /tmp/pip-ephem-wheel-cache-9hmt54fa/wheels/a4/be/16/33fd78bfd1b62703cfeed7bd5f2591504973c5ac446f94f4ef
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Successfully built wheel MarkupSafe
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Installing collected packages: wheel, MarkupSafe
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Attempting uninstall: wheel
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60     Found existing installation: wheel 0.34.2
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60     Uninstalling wheel-0.34.2:
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60       Successfully uninstalled wheel-0.34.2
2024-03-14 14:14:56 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Successfully installed MarkupSafe-2.0.1 wheel-0.33.6
2024-03-14 14:14:57 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Looking in links: wheelhouse
2024-03-14 14:14:57 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/pyaml-21.10.1.tar.gz
2024-03-14 14:14:57 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/PyYAML-5.3.1.tar.gz
2024-03-14 14:14:57 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/psutil-5.9.2.tar.gz
2024-03-14 14:14:58 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/Jinja2-2.11.0.tar.gz
2024-03-14 14:14:58 DEBUG unit.content-cache/0.upgrade-charm logger.go:60 Processing ./wheelhouse/immutables-0.19.tar.gz
2024-03-14 14:14:58 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Installing build dependencies: started
2024-03-14 14:14:58 DEBUG unit.content-cache/0.upgrade-charm logger.go:60   Installing build dependencies: finished with status 'error'
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   ERROR: Command errored out with exit status 1:
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60    command: /var/lib/juju/agents/unit-content-cache-0/.venv/bin/python /var/lib/juju/agents/unit-content-cache-0/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3yrnp0s0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse -- 'setuptools>=42' wheel
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60        cwd: None
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   Complete output (3 lines):
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   Looking in links: wheelhouse
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   ERROR: Could not find a version that satisfies the requirement setuptools>=42 (from versions: 41.6.0)
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   ERROR: No matching distribution found for setuptools>=42
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60   ----------------------------------------
2024-03-14 14:14:58 WARNING unit.content-cache/0.upgrade-charm logger.go:60 ERROR: Command errored out with exit status 1: /var/lib/juju/agents/unit-content-cache-0/.venv/bin/python /var/lib/juju/agents/unit-content-cache-0/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3yrnp0s0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse -- 'setuptools>=42' wheel Check the logs for full command output.
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60 Traceback (most recent call last):
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60   File "/var/lib/juju/agents/unit-content-cache-0/charm/hooks/upgrade-charm", line 8, in <module>
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60     basic.bootstrap_charm_deps()
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60   File "/var/lib/juju/agents/unit-content-cache-0/charm/lib/charms/layer/basic.py", line 226, in bootstrap_charm_deps
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60     raise CalledProcessError(retcode, cmd)
2024-03-14 14:14:59 WARNING unit.content-cache/0.upgrade-charm logger.go:60 subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-content-cache-0/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'pyaml==21.10.1', 'PyYAML==5.3.1', 'psutil==5.9.2', 'Jinja2==2.11.0', 'immutables==0.19', 'pbr==6.0.0', 'contextvars==2.4', 'charms.reactive==1.5.2', 'sniffio==1.2.0', 'typing-extensions==4.1.1', 'charmhelpers==1.2.1', 'Cython==0.29.37', 'netaddr==0.7.19']' returned non-zero exit status 1.

```
Prior:

```
ubuntu@prod-ubuntu-archive-1:/var/lib/juju/agents/unit-content-cache-0/charm$ ls wheelhouse | tee
Cython-0.29.36.tar.gz
Jinja2-2.11.0.tar.gz
MarkupSafe-2.0.1.tar.gz
PyYAML-5.3.1.tar.gz
charmhelpers-1.2.1.tar.gz
charms.reactive-1.5.2.tar.gz
netaddr-0.7.19.tar.gz
pbr-5.11.1.tar.gz
pip-18.1.tar.gz
psutil-5.9.2.tar.gz
pyaml-21.10.1.tar.gz
setuptools-41.6.0.zip
setuptools_scm-1.17.0.tar.gz
wheel-0.33.6.tar.gz
ubuntu@prod-ubuntu-archive-1:/var/lib/juju/agents/unit-content-cache-0/charm
```

Now:

```
ubuntu@prod-ubuntu-archive-1:/var/lib/juju/agents/unit-content-cache-0/charm/wheelhouse$ ls | tee
Cython-0.29.37.tar.gz
Jinja2-2.11.0.tar.gz
MarkupSafe-2.0.1.tar.gz
PyYAML-5.3.1.tar.gz
charmhelpers-1.2.1.tar.gz
charms.reactive-1.5.2.tar.gz
contextvars-2.4.tar.gz
immutables-0.19.tar.gz
netaddr-0.7.19.tar.gz
pbr-6.0.0.tar.gz
pip-18.1.tar.gz
psutil-5.9.2.tar.gz
pyaml-21.10.1.tar.gz
setuptools-41.6.0.zip
setuptools_scm-1.17.0.tar.gz
sniffio-1.2.0.tar.gz
typing_extensions-4.1.1.tar.gz
wheel-0.33.6.tar.gz
ubuntu@prod-ubuntu-archive-1:/var/lib/juju/agents/unit-content-cache-0/charm/wheelhouse$
```

The latest has the following:

```
contextvars-2.4.tar.gz
immutables-0.19.tar.gz
sniffio-1.2.0.tar.gz
typing_extensions-4.1.1.tar.gz
```

This looks to be from https://github.com/canonical/layer-basic/pull/221

Pulling in `sniffio` pulls in `contextvars` which then pulls in `immutables` but the latest wants `setuptools>=42` per https://github.com/MagicStack/immutables/blob/v0.19/pyproject.toml#L2C14-L2C28

**Comment by hloeung** [comment]
`sudo rm contextvars-2.4.tar.gz immutables-0.19.tar.gz sniffio-1.2.0.tar.gz typing_extensions-4.1.1.tar.gz` fixes it for me.

**Comment by ajkavanagh** [comment]
So focal is python 3.6.10 by default, which is really old now and thus modules are stopping supporting it.  The best thing to do is to actually pin the offending python module that is pulling in sniffio in the charm's wheelhouse.txt. It's not clear to me what is bringing in sniffio.

**Comment by ajkavanagh** [comment]
Ah, I see it's a requirement of the charm; yes, you should definitely pin it there.  re the `python_version` thing, looking at the pip source, it only looks at major.minor and ignores patch.  It's an odd pin though, I would expect:

```
sniffio<1.3.1; python_version < '3.9'
```

or something similar; i.e. newer versions of python get newer modules.

**Comment by hloeung** [comment]
> Ah, I see it's a requirement of the charm; yes, you should definitely pin it there. re the `python_version` thing, looking at the pip source, it only looks at major.minor and ignores patch. It's an odd pin though, I would expect:
> 
> ```
> sniffio<1.3.1; python_version < '3.9'
> ```
> 
> or something similar; i.e. newer versions of python get newer modules.

But it's tied in with `anyio` per https://github.com/canonical/layer-basic/pull/221. `anyio` is only added for `python_version => 3.8` so it should match.

Currently:

```
# https://github.com/python-trio/sniffio/pull/49
anyio<3.7.0;python_version >= '3.8'
sniffio<1.3.1  # 1.3.1 requires setuptools>=64
```

I think should be:

```
# https://github.com/python-trio/sniffio/pull/49
anyio<3.7.0;python_version >= '3.8'
sniffio<1.3.1;python_version >= '3.8'  # 1.3.1 requires setuptools>=64
```

So `sniffio` is only added with `anyio` which is `python_version >= '3.8'`. Thoughts @addyess ?

**Comment by addyess** [comment]
Sure.  LGTM i think that should be safe.  sniffio is tied as a dep to anyio

**Comment by ajkavanagh** [comment]
@hloeung no, I still think it is wrong to specify a lower bound pin, with an unbounded python_version pin.  It means that you could have sniffio 4.7 (say it existed) with python 3.6, but forever hold sniffio at 1.3.0 for python 3.24 (at some undefinable point in the future).

The point of the pin is to fix it for some versions of python.  Thus if only Python 3.8 requires sniffio 1.3.1, then the bound should be `python_version ==  '3.8'` although I prefer lower bound pins, personally.

If python 3.10 allows later versions of sniffio, then two lines are put in:

```
sniffio<1.3.1; python_version < '3.9'
sniffio; python_version >= '3.10'
```

etc.

**Comment by chanchiwai-ray** [comment]
This issue also affects https://code.launchpad.net/~al3jandrosg/charm-telegraf/+git/charm-telegraf/+merge/460245

**Comment by ajkavanagh** [comment]
> This issue also affects https://code.launchpad.net/~al3jandrosg/charm-telegraf/+git/charm-telegraf/+merge/460245. If it's possible, we would like this to be resolved since it blocks us from adding this feature into charm-telegraf, and releasing it as part of 24.04 release. Thanks in advance!

Please could you pin sniffio in your `wheelhouse.txt`.  This will provide you with a workaround.  If this doesn't work for you, then please let us know here.  Thanks.

**Comment by hloeung** [comment]
@ajkavanagh but it's not needed though. It was currently just this:

`anyio<3.7.0;python_version >= '3.8'`

`sniffio` is only needed for `anyio` and that is only pulled in and pinned for python >= 3.8. So I think it should follow the same thing and be to match `anyio`:

`sniffio<1.3.1;python_version >= '3.8'`

**Comment by ajkavanagh** [comment]
> @ajkavanagh but it's not needed though. It was currently just this:
> 
> `anyio<3.7.0;python_version >= '3.8'`
> 
> `sniffio` is only needed for `anyio` and that is only pulled in and pinned for python >= 3.8. So I think it should follow the same thing and be to match `anyio`:
> 
> `sniffio<1.3.1;python_version >= '3.8'`

No, please do not pin sniffio for every future version of Python.  Only pin it for the version(s) that you need on a lower bound version of python_version.

Looking at the current  `wheelhouse.txt`, the pins are a bit of a mess as they do pin packages for all future versions of Python; this ostensibly is wrong, sadly; they should all be lower bound pin on python_version with an unpinned version of the library for later python versions.  Otherwise, future versions of Python will definitely break.  I'd do an override it your `wheelhouse.txt` to pin sniffio and anyio to the version you want/need for the python_version you are building for.

**Comment by chanchiwai-ray** [comment]
@ajkavanagh adding it to our charm's wheelhouse

```
sniffio<1.3.1; python_version < '3.9'
sniffio; python_version >= '3.10'
```
gives the following (focal and jammy)

```
unit-telegraf-focal-5: 10:48:47 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   error: subprocess-exited-with-error
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   × pip subprocess to install build dependencies did not run successfully.
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   │ exit code: 1
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   ╰─> [3 lines of output]
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install       Looking in links: wheelhouse
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install       ERROR: Could not find a version that satisfies the requirement flit_core<4,>=3.4 (from versions: none)
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install       ERROR: No matching distribution found for flit_core<4,>=3.4
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install       [end of output]
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   note: This error originates from a subprocess, and is likely not a problem with pip.
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install error: subprocess-exited-with-error
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install 
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install × pip subprocess to install build dependencies did not run successfully.
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install │ exit code: 1
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install ╰─> See above for output.
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install 
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install note: This error originates from a subprocess, and is likely not a problem with pip.
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install Traceback (most recent call last):
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   File "/var/lib/juju/agents/unit-telegraf-jammy-5/charm/hooks/install", line 8, in <module>
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install     basic.bootstrap_charm_deps()
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   File "/var/lib/juju/agents/unit-telegraf-jammy-5/charm/lib/charms/layer/basic.py", line 226, in bootstrap_charm_deps
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install     raise CalledProcessError(retcode, cmd)
unit-telegraf-jammy-5: 10:48:50 WARNING unit.telegraf-jammy/5.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-telegraf-jammy-5/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'chardet==3.0.4', 'certifi==2024.2.2', 'Cython==0.29.37', 'pyaml==21.10.1', 'typing-extensions==4.1.1', 'Jinja2==3.0.3', 'charmhelpers==1.2.1', 'defusedxml==0.5.0', 'redis==3.3.11', 'netaddr==0.7.19', 'pbr==6.0.0', 'requests==2.21.0', 'sniffio==1.2.0', 'lockfile==0.12.2', 'insights-core==3.3.16', 'tenacity==5.0.3', 'contextvars==2.4', 'msgpack==1.0.3', 'six==1.16.0', 'charms.reactive==1.5.2', 'urllib3==1.24.3', 'CacheControl==0.12.6', 'PyYAML==5.3.1', 'idna==2.8', 'immutables==0.19']' returned non-zero exit status 1.
unit-telegraf-jammy-5: 10:48:51 ERROR juju.worker.uniter.operation hook "install" (via explicit, bespoke hook script) failed: exit status 1
unit-telegraf-jammy-5: 10:48:51 INFO juju.worker.uniter awaiting error resolution for "install" hook
^[[A^[[Aunit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   ERROR: Command errored out with exit status 1:
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install    command: /var/lib/juju/agents/unit-telegraf-focal-5/.venv/bin/python /var/lib/juju/agents/unit-telegraf-focal-5/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-x94psjda/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse -- 'setuptools>=42' wheel
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install        cwd: None
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   Complete output (3 lines):
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   Looking in links: wheelhouse
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   ERROR: Could not find a version that satisfies the requirement setuptools>=42 (from versions: 41.6.0)
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   ERROR: No matching distribution found for setuptools>=42
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   ----------------------------------------
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install ERROR: Command errored out with exit status 1: /var/lib/juju/agents/unit-telegraf-focal-5/.venv/bin/python /var/lib/juju/agents/unit-telegraf-focal-5/.venv/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-x94psjda/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index --find-links wheelhouse -- 'setuptools>=42' wheel Check the logs for full command output.
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install Traceback (most recent call last):
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   File "/var/lib/juju/agents/unit-telegraf-focal-5/charm/hooks/install", line 8, in <module>
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install     basic.bootstrap_charm_deps()
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   File "/var/lib/juju/agents/unit-telegraf-focal-5/charm/lib/charms/layer/basic.py", line 226, in bootstrap_charm_deps
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install     check_call([pip, 'install', '-U', reinstall_flag, '--no-index',
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install     raise CalledProcessError(retcode, cmd)
unit-telegraf-focal-5: 10:49:01 WARNING unit.telegraf-focal/5.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-telegraf-focal-5/.venv/bin/pip', 'install', '-U', '--force-reinstall', '--no-index', '--no-cache-dir', '-f', 'wheelhouse', 'contextvars==2.4', 'charmhelpers==1.2.1', 'idna==2.8', 'six==1.16.0', 'pyaml==21.10.1', 'lockfile==0.12.2', 'certifi==2024.2.2', 'Cython==0.29.37', 'chardet==3.0.4', 'PyYAML==5.3.1', 'CacheControl==0.12.6', 'requests==2.21.0', 'netaddr==0.7.19', 'charms.reactive==1.5.2', 'redis==3.3.11', 'tenacity==5.0.3', 'sniffio==1.2.0', 'immutables==0.19', 'pbr==6.0.0', 'msgpack==1.0.3', 'insights-core==3.3.16', 'Jinja2==3.0.3', 'urllib3==1.24.3', 'defusedxml==0.5.0', 'typing-extensions==4.1.1']' returned non-zero exit status 1.
```

**Comment by samuelallan72** [comment]
Note: the sniffio pinning being discussed above was implemented and merged in https://github.com/canonical/layer-basic/pull/224

**Comment by samuelallan72** [comment]
> Pulling in sniffio pulls in contextvars which then pulls in immutables but the latest wants setuptools>=42 per https://github.com/MagicStack/immutables/blob/v0.19/pyproject.toml#L2C14-L2C28

Note that pinning sniffio was a red herring, because the real issue is immutables pulling in setuptools>=42.

**Comment by samuelallan72** [comment]
Pinning `immutables<0.16` in wheelhouse.txt should fix this issue.

**Comment by samuelallan72** [comment]
We also have issues with flit_core - on focal, we can fix installation by adding this to wheelhouse.txt:

```
immutables<0.16
flit_core<4.0.0
```

**Comment by hloeung** [comment]
As I said earlier, `sniffio` pulls in `contextvars` which then pulls in `immutables`. `sniffio` is needed by the `anyio` addition.

I think we only want `sniffio` for Python 3.8 and above to match the `anyio` change so:

```
# https://github.com/python-trio/sniffio/pull/49
anyio<3.7.0;python_version >= '3.8' and python_version < '3.12'
sniffio<1.3.1;python_version >= '3.8' and python_version < '3.12'
```

Whatever `anyio` is, should be the same pinning for `sniffio`, IMO.
